// <auto-generated />
namespace CentroCapacitacionEmergencias.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class CrearTablaDestrezasCursosEva2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CrearTablaDestrezasCursosEva2));
        
        string IMigrationMetadata.Id
        {
            get { return "202603170400131_CrearTablaDestrezasCursosEva2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
